---
- name: Install Build Dependencies
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - build-essential
    - intltool
    - libevent-dev
    - libfuse-dev
    - libglib2.0-dev
    - libmagic-dev
    - libxml2-dev
    - pkg-config

- name: Install libssl-dev
  apt:
    state: latest
    pkg: libssl-dev
    default_release: '1.0.*'
    update_cache: yes

- name: Clone Repository
  git:
    repo: 'https://github.com/skoobe/riofs.git'
    dest: "{{ riofs_build_path }}"

- name: Build | autogen
  command: ./autogen.sh
  args:
    chdir: "{{ riofs_build_path }}"
    creates: "{{ riofs_build_path }}/configure"

- name: Build | configure
  command: ./configure
  args:
    chdir: "{{ riofs_build_path }}"
    creates: "{{ riofs_build_path }}/Makefile"

- name: Build | make
  command: make
  args:
    chdir: "{{ riofs_build_path }}"
    creates: "{{ riofs_build_path }}/src/riofs"

- name: Install | make install
  command: make install
  args:
    chdir: "{{ riofs_build_path }}"
    creates: "{{ '/usr/local/bin/riofs' if not riofs_always_reinstall else omit }}"
  notify: service | riofs | restarted

- name: Cleanup | make clean
  command: make clean
  args:
    chdir: "{{ riofs_build_path }}"
  when: riofs_clean_after_build
